CREATE OR REPLACE TRIGGER display_salary_changes
BEFORE DELETE OR INSERT OR UPDATE ON EMP
FOR EACH ROW
WHEN (NEW.SAL > OLD.SAL * 0.1)
DECLARE
  sal_diff NUMBER;
BEGIN
  DBMS_OUTPUT.PUT_LINE(:OLD.SAL);
  DBMS_OUTPUT.PUT_LINE(:NEW.SAL);
  DBMS_OUTPUT.PUT_LINE(:NEW.EMPNO);
  DBMS_OUTPUT.PUT_LINE(:NEW.ENAME);
  DBMS_OUTPUT.PUT_LINE(:NEW.JOB);
  DBMS_OUTPUT.PUT_LINE(:NEW.MGR);
  DBMS_OUTPUT.PUT_LINE(:NEW.HIREDATE);
  DBMS_OUTPUT.PUT_LINE(:NEW.SAL);
  DBMS_OUTPUT.PUT_LINE(:NEW.COMM);
  DBMS_OUTPUT.PUT_LINE(:NEW.DEPTNO);
END;

UPDATE emp SET sal = 15000
WHERE ename = 'KING';
