CREATE OR REPLACE TRIGGER DATA_DEL
BEFORE DELETE ON dept
FOR EACH ROW
BEGIN
  DELETE FROM emp WHERE deptno = 20;
  DBMS_OUTPUT.PUT_LINE('Data Deleted');
END;

DELETE FROM dept
WHERE deptno = 20;
