DECLARE
  CURSOR c_emp IS
    SELECT * FROM emp WHERE SAL > 3500 AND DEPTNO = 30;
BEGIN
  FOR v_c IN c_emp LOOP
    DBMS_OUTPUT.PUT_LINE(v_c.ename);
    DBMS_OUTPUT.PUT_LINE(v_c.EMPNO);
    DBMS_OUTPUT.PUT_LINE(v_c.JOB);
    DBMS_OUTPUT.PUT_LINE(v_c.MGR);
    DBMS_OUTPUT.PUT_LINE(v_c.HIREDATE);
    DBMS_OUTPUT.PUT_LINE(v_c.SAL);
    DBMS_OUTPUT.PUT_LINE(v_c.COMM);
    DBMS_OUTPUT.PUT_LINE(v_c.DEPTNO);
  END LOOP;
END;
